### ISSUE TITLE
get_eec_state_from_cmd() called every 20 ms, causing unacceptable CPU load 

### ISSUE THREAD

**Issue by rollebolle** [intel/synce4l#20]
For each interface, `synce_clock_poll()` looks for clock state updates every 20 ms. In the end every call results in a `popen()` and `pclose()`, which can be really resource heavy in embedded systems. I think some sort of of alternative to this approach for updating the state should be added, perhaps giving a filename and using `inotify` on it or similar, or having the poll time parameterized. Happy to supply a PR if this sounds like a good idea.

**Comment by mmichaliINTC** [comment]
Hi - I agree that is not the best solution, that sounds like a great idea. The problem is it's only a temporary solution. We are waiting with our breaths bated for the official kernel DPLL interface which is being finalized as we speak: https://lore.kernel.org/netdev/20230720091903.297066-11-vadim.fedorenko@linux.dev/T/
We are waiting for the next version and after that we would implement this support in `synce4l`.

But I believe we should support the both in-tree DPLL kernel interface and legacy solution (polling for a command) in the transition period. Maybe adding a programable poll period is a good idea? Would be great to see such a PR!

Btw. I don't think that `inotify` would solve it - because it don't have to be a file read, but any arbitrary command.

**Comment by rollebolle** [comment]
Ah yes you are correct that inotify wouldn't fix the problem. And great that official support is underway. I guess you still would plan on keeping the current solution as an alternative, for those stuck with an older kernel version?

**Comment by mmichaliINTC** [comment]
Yes, as I said - we are planning to keep the old solution for some time (not decided yet how long) for those who have older kernels. I'm perfectly aware that most of the distributions will be shipped with older kernel version out-of-the-box for years to come - we need to support them.
